apiVersion: v1
kind: Template
metadata:
  name: mi-scheduler
  labels:
    app: mi-scheduler
  annotations:
    thoth-station.ninja/template-version: 0.1.0
    description: >
      mi-scheduler CronJob, schedules workflows for all repositories found
      in repositories-configMap
    openshift.io/display-name: 'Scheduler Cronjob'
    version: 0.0.1
    tags: mi-scheduler
    template.openshift.io/long-description: >
      mi-scheduler CronJob, schedules workflows for all repositories found
      in repositories-configMap
    template.openshift.io/provider-display-name: Red Hat, Inc.

parameters:
  - description: Registry the ImageStream to be use lives in
    displayName: ImageStream Registry
    required: true
    name: IMAGE_STREAM_REGISTRY
    value: "docker-registry.default.svc:5000"

  - description: Project the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE
    value: "dtuchyna-thoth-dev"

  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

objects:
  - kind: CronJob
    apiVersion: batch/v1beta1
    metadata:
      name: mi-scheduler
      labels:
        app: mi-scheduler
      annotations:
        thoth-station.ninja/template-version: 0.1.0
    spec:
      schedule: "0 0 * * 0"
      jobTemplate:
        metadata:
          name: srcopsmetrics
        spec:
          template:
            spec:
              containers:
                - image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/mi-scheduler:${IMAGE_STREAM_TAG}"
                  name: srcopsmetrics
                  command: ["mi-scheduler"]
                  args: ["-r", ${REPOSITORIES}, "-o", ${ORGANIZATIONS}]
                  env:
                    - name: APP_FILE
                      value: "./app.py"
                    - name: REPOSITORIES
                      valueFrom:
                        secretKeyRef:
                          name: srcopsmetrics-repositories
                          key: repositories
                    - name: ORGANIZATIONS
                      valueFrom:
                        configMapRef:
                          name: srcopsmetrics-repositories
                          key: organizations
              restartPolicy: OnFailure
