apiVersion: v1
kind: Template
metadata:
  name: mi-scheduler
  labels:
    app: mi-scheduler
  annotations:
    thoth-station.ninja/template-version: 0.1.0
    description: >
      mi-scheduler CronJob, schedules workflows for all repositories found
      in repositories-configMap
    openshift.io/display-name: 'Scheduler Cronjob'
    version: 0.0.1
    tags: mi-scheduler
    template.openshift.io/long-description: >
      mi-scheduler CronJob, schedules workflows for all repositories found
      in repositories-configMap
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: mi-scheduler
      labels:
        app: mi-scheduler
      annotations:
        thoth-station.ninja/template-version: 0.1.0
    spec:
      lookupPolicy:
        local: false
