apiVersion: v1
kind: Template
metadata:
  name: srcopsmetrics-repositories
  annotations:
    description: >
      SrcOpsMetrics Repositories ConfigMap - all of the repositories inspected by SrcOpsMetrics CronJob
    openshift.io/display-name: SrcOpsMetrics Repositories
    version: 0.0.1
    tags: srcopsmetrics
    template.openshift.io/documentation-url: https://github.com/AICoE/SrcOpsMetrics
    template.openshift.io/long-description: >
      This template defines public environment variables required to run SrcOpsMetrics CronJob on OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    app: srcopsmetrics

parameters:
  - description: All of the repositories that are inspected by SrcOpsMetrics CronJob
    displayName: Repositories List
    required: true
    name: repositories
    value: "None"

  - description: All of the organizations that are inspected by SrcOpsMetrics CronJob
    displayName: Organizations List
    required: true
    name: organizations
    value: "thoth-station,AICoE"

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: srcopsmetrics
      labels:
        app: srcopsmetrics
    data:
      bucket: ${CEPH_BUCKET}
      host: ${S3_ENDPOINT_URL}
      prefix: ${CEPH_BUCKET_PREFIX}
